export const API_ENDPOINTS = {
    EXPERIENCES: '/experiences',
    SHOWTIMES: (id) => `/showtimes/movie/${id}`,
    ALL_SHOWTIMES: '/showtimes/all',
    CINEMAS: '/cinemas',
    MOVIES: '/movies',
    NOW_SHOWING: (p) => `/movies/now-showing?page=${p}`,
    COMING_SOON: (p) => `/movies/coming-soon?page=${p}`,
    MOVIE_DETAILS: (id) => `/movies/${id}`,
    SINGLE_SHOWTIME: (id) => `/showtimes/${id}`,
    LOGIN: '/auth/login',
    REGISTER: '/auth/register',
    ME: '/auth/me',
    VERIFY_RESET_TOKEN: (token) => `/auth/verify-reset-token/${token}`,
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
    FAQS: '/faqs',
    VEHICLES: '/vehicles',
    VEHICLE_DETAILS: (id) => `/vehicles/${id}`,
    BOOKINGS: '/bookings',
    MY_BOOKINGS: '/bookings/me',
    BOOKING_DETAILS: (id) => `/bookings/${id}`,
    PROCESS_PAYMENT: '/payments/process',
    PAYMENTS: '/payments',
    LOCKED_SEATS: (showtimeId) => `/bookings/locked-seats/${showtimeId}`,
    LOCKED_PARKING: (showtimeId) => `/bookings/locked-parking/${showtimeId}`,
    TICKETS: '/ticket',
    TICKET_DETAILS: (id) => `/ticket/${id}`,
    REVIEWS: '/reviews',
    REVIEWS_BY_MOVIE: (movieId) => `/reviews/${movieId}`,

};
